### PR TITLE
Update it to make Blazor Server work

### PR DESCRIPTION
**Pull request by HugoVG**
made ``IBlazorCurrentDeviceService`` a scoped service, scoped sevices will be changed to singleton for webassembly since only one scope will be made anyway. 
changed stuff in readme to make Blazor Server usage a little more clear

### CODE REVIEW

**Comment by HugoVG** [comment]
fixes https://github.com/arivera12/BlazorCurrentDevice/issues/5

**Comment by arivera12** [comment]
I will take a look soon, I have been off a while...

**Comment by ledpup** [comment]
> I will take a look soon, I have been off a while...

I am having this issue described above too, after trying to convert my project from Blazor WASM to .NET 8 and InteractiveAuto (Server and WASM). I haven't gotten everything running yet but this seems like a safe PR to merge in.

**Comment by HugoVG** [comment]
bump

**Comment by JackBasta** [comment]
+1 to get this merged too - we're upgrading from .net 7 WASM to .NET 8 server/interactiveauto

**Comment by ledpup** [comment]
It would be very nice to have this merged in. I have the code included in my app at the moment. I guess I could fork, but this fix definitely works. If we had this merged and put out to NuGet I could start using it again.

**Comment by HugoVG** [comment]
@ledpup @JackBasta sorry for the ping andlong wait, I finally had a day off in a while and could work on this thing, I've remade most of it, sadly not everything got port over like NodeJS or FireFoxOS, but I did manage to rewrite it in 100% C#, I uploaded the Nuget packages under a different repository on Nuget 
[It's Here now](https://www.nuget.org/packages/CurrentDevice/1.0.0#readme-body-tab)
And the Github project [here](https://github.com/HugoVG/CurrentDevice)
- It might take a bit to verify
- I verified this works on Server and WASM
- I added Sample project for Server and WASM 
- Added Usage guides for Server and WASM (if you use auto it shouldn't really matter)

**Pull request closed without merging**
